version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow
    volumes:
      - "./data/database:/var/lib/postgresql/data"
    ports:
      - "5432:5432"