version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
    volumes:
      - "./data/database:/var/lib/postgresql/data"
    expose:
      - "5432"
    secrets:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
  backend:
    restart: always
    build:
      context: .
    image: airflow_server
    depends_on:
      - db
    entrypoint: []
    command: ["sh", "-c", "./wait-for-it.sh -t 60 db:5432 -- \
     airflow initdb \
     && airflow connections --add --conn_id 'sms' --conn_uri $$(cat /run/secrets/TWILIO_ENDPOINT) \
     && airflow unpause weather_bot \
     && airflow scheduler"]
    ports:
      - "8080:8080"
    environment:
      ACCOUNT_SID_FILE: /run/secrets/ACCOUNT_SID
      FROM_PHONE_NUMBER_FILE: /run/secrets/FROM_PHONE_NUMBER
      OPEN_WEATHER_API_KEY_FILE: /run/secrets/OPEN_WEATHER_API_KEY
      POSTGRES_ADDRESS: db
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      TO_PHONE_NUMBER_FILE: /run/secrets/TO_PHONE_NUMBER
      TWILIO_ENDPOINT_FILE: /run/secrets/TWILIO_ENDPOINT
    volumes:
    - "./data/logs:/opt/airflow/logs"
    secrets:
      - ACCOUNT_SID
      - FROM_PHONE_NUMBER
      - OPEN_WEATHER_API_KEY
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - TO_PHONE_NUMBER
      - TWILIO_ENDPOINT

secrets:
  ACCOUNT_SID:
    file: secrets/ACCOUNT_SID.txt
  FROM_PHONE_NUMBER:
    file: secrets/FROM_PHONE_NUMBER.txt
  OPEN_WEATHER_API_KEY:
    file: secrets/OPEN_WEATHER_API_KEY.txt
  POSTGRES_DB:
    file: secrets/POSTGRES_DB.txt
  POSTGRES_PASSWORD:
    file: secrets/POSTGRES_PASSWORD.txt
  POSTGRES_USER:
    file: secrets/POSTGRES_USER.txt
  TO_PHONE_NUMBER:
    file: secrets/TO_PHONE_NUMBER.txt
  TWILIO_ENDPOINT:
    file: secrets/TWILIO_ENDPOINT.txt