version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
    volumes:
      - "./data/database:/var/lib/postgresql/data"
    expose:
      - "5432"
    secrets:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
  backend:
    restart: always
    build:
      context: .
    image: airflow_server
    depends_on:
      - db
    entrypoint: []
    command: ["sh", "-c", "./wait-for-it.sh -t 60 db:5432 -- \
     airflow initdb \
     && airflow connections --add --conn_id 'twilio' \
     --conn_uri http://$$(cat $$TWILIO_ACCOUNT_SID_FILE):$$(cat $$TWILIO_AUTH_TOKEN_FILE)@https%3A%2F%2Fapi.twilio.com \
     && airflow unpause weather_bot \
     && airflow scheduler"]
    ports:
      - "8080:8080"
    environment:
      OPEN_WEATHER_MAP_API_KEY_FILE: /run/secrets/OPEN_WEATHER_MAP_API_KEY
      PERSONAL_PHONE_NUMBER_FILE: /run/secrets/PERSONAL_PHONE_NUMBER
      POSTGRES_ADDRESS: db
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      TWILIO_ACCOUNT_SID_FILE: /run/secrets/TWILIO_ACCOUNT_SID
      TWILIO_AUTH_TOKEN_FILE: /run/secrets/TWILIO_AUTH_TOKEN
      TWILIO_PHONE_NUMBER_FILE: /run/secrets/TWILIO_PHONE_NUMBER
    volumes:
    - "./data/logs:/opt/airflow/logs"
    secrets:
      - OPEN_WEATHER_MAP_API_KEY
      - PERSONAL_PHONE_NUMBER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TWILIO_PHONE_NUMBER

secrets:
  OPEN_WEATHER_MAP_API_KEY:
    file: secrets/OPEN_WEATHER_MAP_API_KEY.txt
  PERSONAL_PHONE_NUMBER:
    file: secrets/PERSONAL_PHONE_NUMBER.txt
  POSTGRES_DB:
    file: secrets/POSTGRES_DB.txt
  POSTGRES_PASSWORD:
    file: secrets/POSTGRES_PASSWORD.txt
  POSTGRES_USER:
    file: secrets/POSTGRES_USER.txt
  TWILIO_ACCOUNT_SID:
    file: secrets/TWILIO_ACCOUNT_SID.txt
  TWILIO_AUTH_TOKEN:
    file: secrets/TWILIO_AUTH_TOKEN.txt
  TWILIO_PHONE_NUMBER:
    file: secrets/TWILIO_PHONE_NUMBER.txt
